# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Node.js CI

on:
  push:
    branches: [ devel ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version:
        - "14.x"
        - "16.x"
        - "17.x"
        - '18.x'

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@master
      with:
        cache: npm
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci
    - name: Run the tests
      run: npm test
    - name: Check types definition
      run: npm run check-dts
